-- ============================================================
--  P6 추가 테이블 DDL (Oracle)
--  대상: INQUIRY, PENALTY_HISTORY, ADMIN_LOG,
--         DAILY_STATS, CHATBOT_SESSION, CHATBOT_MESSAGE
--
--  실행 전제: MEMBER, ADMIN, RESTAURANT_REVIEWS 테이블 존재
--  실행 순서: 시퀀스 → 테이블 → 인덱스 → 코멘트
-- ============================================================


-- ────────────────────────────────────────────────────────────
--  1. SEQUENCES
-- ────────────────────────────────────────────────────────────

CREATE SEQUENCE SEQ_INQUIRY
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE SEQUENCE SEQ_PENALTY_HISTORY
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE SEQUENCE SEQ_ADMIN_LOG
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE SEQUENCE SEQ_DAILY_STATS
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE SEQUENCE SEQ_CHATBOT_SESSION
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE SEQUENCE SEQ_CHATBOT_MESSAGE
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;


-- ────────────────────────────────────────────────────────────
--  2. TABLES
-- ────────────────────────────────────────────────────────────

-- 2-1. INQUIRY (1:1 문의)
CREATE TABLE INQUIRY (
    INQUIRY_ID   NUMBER          NOT NULL,
    MEMBER_ID    NUMBER          NOT NULL,
    TITLE        VARCHAR2(200)   NOT NULL,
    CONTENT      VARCHAR2(2000)  NOT NULL,
    STATUS       VARCHAR2(10)    DEFAULT 'PENDING' NOT NULL,  -- PENDING / ANSWERED
    ANSWER       VARCHAR2(2000),
    ANSWERED_AT  TIMESTAMP,
    INSERT_TIME  TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATE_TIME  TIMESTAMP,
    CONSTRAINT PK_INQUIRY        PRIMARY KEY (INQUIRY_ID),
    CONSTRAINT FK_INQUIRY_MEMBER FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER (MEMBER_ID),
    CONSTRAINT CK_INQUIRY_STATUS CHECK (STATUS IN ('PENDING', 'ANSWERED'))
);

-- 2-2. PENALTY_HISTORY (패널티 이력)
CREATE TABLE PENALTY_HISTORY (
    PENALTY_ID     NUMBER         NOT NULL,
    MEMBER_ID      NUMBER         NOT NULL,
    REVIEW_ID      NUMBER,                     -- 신고 리뷰 (수동 패널티는 NULL)
    ADMIN_ID       NUMBER,                     -- 처리 관리자 (자동 처리는 NULL)
    PENALTY_REASON VARCHAR2(500)  NOT NULL,
    PENALTY_TYPE   VARCHAR2(10)   NOT NULL,    -- WARNING / SUSPEND
    SUSPEND_DAYS   NUMBER(5),
    INSERT_TIME    TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_PENALTY_HISTORY        PRIMARY KEY (PENALTY_ID),
    CONSTRAINT FK_PENALTY_MEMBER         FOREIGN KEY (MEMBER_ID)  REFERENCES MEMBER (MEMBER_ID),
    CONSTRAINT FK_PENALTY_ADMIN          FOREIGN KEY (ADMIN_ID)   REFERENCES ADMIN  (ADMIN_ID),
    CONSTRAINT CK_PENALTY_TYPE           CHECK (PENALTY_TYPE IN ('WARNING', 'SUSPEND'))
);

-- 2-3. ADMIN_LOG (관리자 행동 로그)
--       패널티 이외 행동: REVIEW_DELETE / NOTICE_CREATE / NOTICE_UPDATE /
--                         NOTICE_DELETE / INQUIRY_ANSWER / ADMIN_GRANT /
--                         ADMIN_REVOKE / MEMBER_SUSPEND / MEMBER_SUSPEND_RELEASE
CREATE TABLE ADMIN_LOG (
    ADMIN_LOG_ID  NUMBER         NOT NULL,
    ADMIN_ID      NUMBER         NOT NULL,
    TARGET_ID     NUMBER,                      -- 조치 대상 엔티티 ID (nullable)
    ADMIN_ACTION  VARCHAR2(30)   NOT NULL,
    ACTION_DETAIL VARCHAR2(500),
    INSERT_TIME   TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_ADMIN_LOG       PRIMARY KEY (ADMIN_LOG_ID),
    CONSTRAINT FK_ADMIN_LOG_ADMIN FOREIGN KEY (ADMIN_ID) REFERENCES ADMIN (ADMIN_ID)
);

-- 2-4. DAILY_STATS (일별 통계 — 스케줄러 매일 01:00 집계)
CREATE TABLE DAILY_STATS (
    STAT_ID           NUMBER    NOT NULL,
    STAT_DATE         DATE      NOT NULL,
    TOTAL_MEMBERS     NUMBER    DEFAULT 0 NOT NULL,
    NEW_MEMBERS       NUMBER    DEFAULT 0 NOT NULL,
    ACTIVE_REVIEWS    NUMBER    DEFAULT 0 NOT NULL,
    TOTAL_INQUIRIES   NUMBER    DEFAULT 0 NOT NULL,
    PENDING_INQUIRIES NUMBER    DEFAULT 0 NOT NULL,
    INSERT_TIME       TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_DAILY_STATS      PRIMARY KEY (STAT_ID),
    CONSTRAINT UQ_DAILY_STATS_DATE UNIQUE (STAT_DATE)
);

-- 2-5. CHATBOT_SESSION (챗봇 대화 세션)
CREATE TABLE CHATBOT_SESSION (
    SESSION_ID  NUMBER    NOT NULL,
    MEMBER_ID   NUMBER    NOT NULL,
    INSERT_TIME TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATE_TIME TIMESTAMP,
    CONSTRAINT PK_CHATBOT_SESSION        PRIMARY KEY (SESSION_ID),
    CONSTRAINT FK_CHATBOT_SESSION_MEMBER FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER (MEMBER_ID)
);

-- 2-6. CHATBOT_MESSAGE (챗봇 대화 메시지)
CREATE TABLE CHATBOT_MESSAGE (
    MESSAGE_ID  NUMBER         NOT NULL,
    SESSION_ID  NUMBER         NOT NULL,
    ROLE        VARCHAR2(10)   NOT NULL,    -- USER / ASSISTANT
    CONTENT     CLOB           NOT NULL,
    INSERT_TIME TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_CHATBOT_MESSAGE         PRIMARY KEY (MESSAGE_ID),
    CONSTRAINT FK_CHATBOT_MESSAGE_SESSION FOREIGN KEY (SESSION_ID) REFERENCES CHATBOT_SESSION (SESSION_ID),
    CONSTRAINT CK_CHATBOT_MESSAGE_ROLE    CHECK (ROLE IN ('USER', 'ASSISTANT'))
);


-- ────────────────────────────────────────────────────────────
--  3. INDEXES  (조회 패턴 기반)
-- ────────────────────────────────────────────────────────────

-- INQUIRY: 회원별 내 문의 목록 조회
CREATE INDEX IDX_INQUIRY_MEMBER     ON INQUIRY        (MEMBER_ID, INSERT_TIME DESC);
-- INQUIRY: 관리자 상태별 필터
CREATE INDEX IDX_INQUIRY_STATUS     ON INQUIRY        (STATUS, INSERT_TIME DESC);

-- PENALTY_HISTORY: 회원별 패널티 이력
CREATE INDEX IDX_PENALTY_MEMBER     ON PENALTY_HISTORY (MEMBER_ID, INSERT_TIME DESC);

-- ADMIN_LOG: 관리자별 로그 조회
CREATE INDEX IDX_ADMIN_LOG_ADMIN    ON ADMIN_LOG       (ADMIN_ID, INSERT_TIME DESC);

-- DAILY_STATS: 날짜 기반 집계 조회 (UNIQUE 이미 있으나 명시)
CREATE INDEX IDX_DAILY_STATS_DATE   ON DAILY_STATS     (STAT_DATE DESC);

-- CHATBOT: 회원별 세션 목록 (최신순)
CREATE INDEX IDX_CHATBOT_SESSION_MBR ON CHATBOT_SESSION (MEMBER_ID, UPDATE_TIME DESC);
-- CHATBOT: 세션별 메시지 시간순
CREATE INDEX IDX_CHATBOT_MSG_SESSION ON CHATBOT_MESSAGE  (SESSION_ID, INSERT_TIME ASC);


-- ────────────────────────────────────────────────────────────
--  4. COMMENTS
-- ────────────────────────────────────────────────────────────

COMMENT ON TABLE  INQUIRY                 IS '1:1 문의';
COMMENT ON COLUMN INQUIRY.STATUS          IS 'PENDING(미답변) / ANSWERED(답변완료)';

COMMENT ON TABLE  PENALTY_HISTORY         IS '패널티 이력 (WARNING/SUSPEND)';
COMMENT ON COLUMN PENALTY_HISTORY.REVIEW_ID   IS '신고 대상 리뷰 ID (수동 패널티는 NULL)';
COMMENT ON COLUMN PENALTY_HISTORY.ADMIN_ID    IS '처리 관리자 ID (자동 처리는 NULL)';

COMMENT ON TABLE  ADMIN_LOG               IS '관리자 행동 로그 (패널티 외 모든 액션)';
COMMENT ON COLUMN ADMIN_LOG.ADMIN_ACTION  IS 'REVIEW_DELETE/NOTICE_CREATE/NOTICE_UPDATE/NOTICE_DELETE/INQUIRY_ANSWER/ADMIN_GRANT/ADMIN_REVOKE/MEMBER_SUSPEND/MEMBER_SUSPEND_RELEASE';

COMMENT ON TABLE  DAILY_STATS             IS '일별 통계 집계 (매일 01:00 스케줄러 실행)';

COMMENT ON TABLE  CHATBOT_SESSION         IS '챗봇 대화 세션';
COMMENT ON TABLE  CHATBOT_MESSAGE         IS '챗봇 대화 메시지';
COMMENT ON COLUMN CHATBOT_MESSAGE.ROLE    IS 'USER(사용자 입력) / ASSISTANT(챗봇 응답)';
COMMENT ON COLUMN CHATBOT_MESSAGE.CONTENT IS '메시지 본문 (CLOB — 긴 응답 대비)';

COMMIT;
